version: '1.0'
services:
  loki:
    image: grafana/loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - loki

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - loki

  rabbitmq:
    image: 'rabbitmq:management'
    ports:
      - '5672:5672'
      - '15672:15672'
    hostname: rabbitmq-dev
    container_name: dev-rabbit
    networks:
      - default

  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 1234
    ports:
      - 27018:27017
    networks:
      - default
    volumes:
      - mongodb_data_container:/data/db

  vault_dev: 
    image: hashicorp/vault:latest
    restart: on-failure:10
    ports:
      - "8201:8201"
    environment:
      VAULT_ADDR: 'https://0.0.0.0:8201/'
      VAULT_LOCAL_CONFIG: '{"listener": [{"tcp":{"address": "0.0.0.0:8201", "tls_disable": "0", "tls_cert_file":"/data/cert.pem", "tls_key_file":"/data/key.pem"}}], "default_lease_ttl": "168h", "max_lease_ttl": "720h", "ui": true}'
      VAULT_DEV_ROOT_TOKEN_ID: '1a2b3c4d-5e6f-7g8h-9i0j-123456789abc'
      VAULT_TOKEN: 'abcdef12-3456-7890-abcd-ef1234567890'
    cap_add:
      - IPC_LOCK
    volumes:
      - ./vault-volume:/data
    healthcheck:
      retries: 5
    command: 'server -dev -dev-root-token-id="1a2b3c4d-5e6f-7g8h-9i0j-123456789abc"'

  vault_setup:
    image: jeffstampe/vaultsetup:latest
    environment:
      - VAULT_IP=https://vault_dev:8201
      - VAULT_SECRET=1a2b3c4d-5e6f-7g8h-9i0j-123456789abc
      - JWTSecret=ThySeven2023PaddingToEnsureLengthAndSecurity123456
      - JWTIssuer=ThySevenIssuer
    depends_on:
      - vault_dev

volumes:
  images:
    external: false
  mongodb_data_container:

networks:
  default:
    driver: bridge
    name: 'mitnet'
  loki:
